# Introduction to Data Science 2026

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [15]:
A = [i for i in range(0, int(1e7-1))]
B = A.copy()
print (A[:10], B[:10], type(A[0]), type(B[0]) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'int'> <class 'int'>


2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [16]:
def add_with_for(A,B):
    C = [n1+n2 for n1, n2 in zip(A,B)]
    return C
res_loop = add_with_for(A,B)
print(res_loop[:10], type(res_loop[0]))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'int'>


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [60]:
import numpy as np
A, B = np.arange(0, 1e7-1), np.arange(0, 1e7-1)
print(A[:10], B[:10], type(A[0]), type(B[0]), '\n')

def add_with_np(A,B):
    return A + B
res_np = add_with_np(A,B)
print(res_np[:10], type(res_np[0]))

# I notice that we can write shorter functions with np. And, np is much faster at not only making the arrays, but also adding the values. Numpy also handles using floats directly unlike the standard list.

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] <class 'numpy.float64'> <class 'numpy.float64'> 

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.] <class 'numpy.float64'>


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [25]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
arr = np.arange(100).reshape((10,10))
print(arr, '\n',repr(arr),'\n', type(arr[0][0]))
     

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]) 
 <class 'numpy.int64'>


2. Create the following array:

In [27]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [40]:
arr = np.tile(np.array([0,1], dtype="float"),(10,5))
print(arr, '\n',repr(arr),'\n', type(arr[0][0]))

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]] 
 array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]]) 
 <class 'numpy.float64'>


3. Create the following array (D):

In [29]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [102]:
A_ones = np.ones((10,10), dtype="float")
print(A_ones, np.shape(A_ones),'\n')
A_ones_diag = np.diagflat(np.repeat([1.], 10))
print(A_ones_diag, np.shape(A_ones_diag))
A_ones_zeros_diag_LR = A_ones - A_ones_diag
print(f"\nFinal 10x10 matrix:\n{A_ones_zeros_diag_LR}\n\nRepr:{repr(A_ones_zeros_diag_LR)}\n\nData type of elements{type(A_ones_zeros_diag_LR[0][0])}")


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (10, 10) 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] (10, 10)

Final 10x10 matrix:
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]


4. Create the following array (E):

In [31]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [105]:
A_ones = np.ones((10,10))
print(A_ones, np.shape(A_ones),'\n')
A_ones_flipped_diag = np.fliplr(np.diagflat(np.repeat([1], 10)))
print(A_ones, np.shape(A_ones_flipped_diag),'\n')
A_ones_zeros_diag_RL = A_ones - A_ones_flipped_diag
print(f"Final 10x10 matrix:\n{A_ones_zeros_diag_RL}\n\nRepr:\n{repr(A_ones_zeros_diag_RL)}\n\nData type of elements{type(A_ones_zeros_diag_RL[0][0])}")


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (10, 10) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (10, 10) 

Final 10x10 matrix:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [133]:
# print(A_ones_zeros_diag_LR,'\n\n', A_ones_zeros_diag_RL, '\n')
D = A_ones_zeros_diag_LR
E = A_ones_zeros_diag_RL


D_det = np.linalg.det(D)
E_det = np.linalg.det(E)
print(f"Determinant of D: {D_det}\nDeterminant of E:{E_det}\nProduct of determinants D and E: {D_det*E_det}")

DE_mult = D@E
DE_det = np.linalg.det(DE_mult)
print(f"DE:\n{DE_mult}\n\n DE determinant:{DE_det}")

Determinant of D: -8.999999999999998
Determinant of E:9.000000000000002
Product of determinants D and E: -81.0
DE:
[[8. 8. 8. 8. 8. 8. 8. 8. 8. 9.]
 [8. 8. 8. 8. 8. 8. 8. 8. 9. 8.]
 [8. 8. 8. 8. 8. 8. 8. 9. 8. 8.]
 [8. 8. 8. 8. 8. 8. 9. 8. 8. 8.]
 [8. 8. 8. 8. 8. 9. 8. 8. 8. 8.]
 [8. 8. 8. 8. 9. 8. 8. 8. 8. 8.]
 [8. 8. 8. 9. 8. 8. 8. 8. 8. 8.]
 [8. 8. 9. 8. 8. 8. 8. 8. 8. 8.]
 [8. 9. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]

 DE determinant:-81.0000000000001


I did not know why this was, so I asked AI (Gemini). It told me that it has to do with the "multiplicative property of determinants", that is true for all square matrices of the same size.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [158]:
import sklearn
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing(as_frame=True)
print(housing.data.shape, np.shape(housing.data))
print(housing.feature_names[:])



(20640, 8) (20640, 8)


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [174]:
print(housing.data.head())
# print(housing.data["AveBedrms"])
avg_2_bedrms = np.where(housing.data["AveBedrms"] > 2)
print(avg_2_bedrms, housing.data.iloc[710])

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  
(array([  710,  1023,  1024,  1030,  1102,  1233,  1234,  1235,  1236,
        1238,  1239,  1240,  1566,  1867,  1871,  1872,  1879,  1881,
        1889,  1901,  1906,  1910,  1911,  1912,  1913,  1914,  1925,
        1926,  1978,  1979,  2392,  2395,  2396,  2397,  2398,  2510,
        2511,  2643,  2656,  2763,  2768,  2776,  2778,  3014,  3086,
        3095,  3258,  3292,  3293,  3313,  3314,  3334,  3349,  3350,
        9193,  9423,  9431,  945

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [186]:
median_house_age_1_3 = np.where((housing.data["HouseAge"] >= 1) & (housing.data["HouseAge"] <= 3))
print(median_house_age_1_3, '\n\n',np.shape(median_house_age_1_3))

(array([   59,   854,   871,   959,   976,  1260,  1565,  1566,  1648,
        1719,  2206,  2310,  2311,  2312,  2336,  2339,  2706,  2774,
        2993,  3130,  3140,  5506,  9109,  9132,  9147,  9168,  9187,
        9378,  9639, 10336, 10376, 10391, 10401, 10403, 10406, 10410,
       10412, 10416, 10440, 10456, 10467, 10513, 10514, 10519, 10521,
       10524, 10525, 10529, 10548, 10619, 10622, 10631, 11490, 11775,
       12000, 12006, 12077, 12084, 12119, 12123, 12137, 12142, 12143,
       12151, 12156, 12167, 12171, 12201, 12202, 12203, 12204, 12285,
       12286, 12308, 12363, 12430, 12841, 12868, 13041, 13074, 13100,
       13102, 13139, 13177, 13179, 13367, 13368, 13373, 13374, 13375,
       13422, 13659, 13713, 13715, 13747, 13848, 13855, 14557, 15220,
       15444, 15464, 15736, 15785, 16383, 16566, 16593, 17068, 17824,
       17826, 17827, 18725, 18942, 18947, 18972, 18989, 19001, 19003,
       19033, 19046, 19536, 19561, 19650, 20070, 20367]),) 

 (1, 124)


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [237]:
median_home_value_grt_25000 = np.where(housing.target > 0.25)
# print(median_home_value_grt_25000)
population_home_value_grt_25000 = housing.data["Population"][median_home_value_grt_25000[0]]
print(population_home_value_grt_25000)
population_mean = np.mean(population_home_value_grt_25000)
print("\n\nPopulation Mean:",population_mean)


0         322.0
1        2401.0
2         496.0
3         558.0
4         565.0
          ...  
20635     845.0
20636     356.0
20637    1007.0
20638     741.0
20639    1387.0
Name: Population, Length: 20630, dtype: float64


Population Mean: 1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [34]:
import pandas as pd

reviews = pd.read_json("./Automotive_5.json", lines=True)
pd.read_json("./Automotive_5.json", lines=True)

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,4,False,"05 1, 2015",A8WEXFRWX1ZHH,0209688726,{'Color:': ' AC'},Goldengate,"After I wrote the below review, the manufactur...",Works well if you place phone in horizontally ...,1430438400,NaN,NaN
1,1,True,"04 19, 2018",ABCA1A8E4DGV1,0209688726,{'Color:': ' Blue'},noe,It sucks barely picks up anything definitely n...,sucks,1524096000,NaN,NaN
2,1,True,"04 16, 2018",A1NX8HM89FRQ32,0209688726,{'Color:': ' Black'},Eduard,"Well to write a short one, it blew 2 fuses of ...",Defective,1523836800,NaN,NaN
3,3,True,"04 13, 2018",A1X77G023NY0KY,0209688726,{'Color:': ' CA'},Lauren,I have absolutely no memory of buying this but...,Looks cool! Probably works,1523577600,NaN,NaN
4,5,True,"04 8, 2018",A3GK37JO2MGW6Q,0209688726,{'Color:': ' Black'},danny,it ok it does it job,Five Stars,1523145600,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1711514,5,True,"06 19, 2018",A3H86E5N0F1Q5R,B01HJFDJ8S,NaN,John Jr,"Fast Shipping, Works Great!",Works Great!,1529366400,NaN,NaN
1711515,4,True,"08 23, 2017",AXH645B4SSAJY,B01HJFDJ8S,NaN,Brian.,"Fit isn't great, relays are very hard to press...",Four Stars,1503446400,NaN,NaN
1711516,5,True,"08 8, 2017",AMGJLCCNVFB8,B01HJFDJ8S,NaN,John M.,I bought an auxiliary horn for my car and it n...,I bought an auxiliary horn for my car and it ...,1502150400,NaN,NaN
1711517,5,True,"08 24, 2018",A1MJUNTX7CTR5U,B01HJI17Y8,{'Size:': ' H8-NEW'},JKPA,Way better than stock. Nice bright and white. ...,"NICE, BRIGHT AND WHITE",1535068800,NaN,[https://images-na.ssl-images-amazon.com/image...


2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [35]:
reviews["reviewText"] = reviews["reviewText"].str.lower()
reviews["reviewText"][0]

"after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications eas

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [40]:
with open("stopwords-en.txt", "r", encoding="utf-8") as file:
    stopwords = file.read().splitlines()
    # stopwords.extend(punctuations)
stopwords = set(stopwords)
print(stopwords)

reviews_stopwords_removed = reviews["reviewText"].fillna("").str.split().apply(lambda review: " ".join([word for word in review if word not in stopwords]))
punctuations_removed = reviews_stopwords_removed.str.replace(r'[^\w\s]', '', regex=True)
reviews["reviewText"] = punctuations_removed
reviews["reviewText"]
#had to get help from gemini on this one. most of the logic comes from pandas docs though. this is very slow, there are definitely optimizations that could be done

{'too', 'there', 'yourself', 'three', 'beforehand', 'eg', 'along', 'can', 'ten', 'either', 'put', 'her', 'may', 'toward', 'move', 'are', 'mill', 'each', 'he', 'full', 'first', 'herein', 'something', 'his', 'go', 'most', 'or', 'though', 'nevertheless', 'always', 'whose', 'anything', 'bottom', 'indeed', 'two', 'these', 'amongst', 'latterly', 'done', 'our', 'therefore', 'was', 'amount', 'becomes', 'and', 'below', 'somewhere', 'very', 'else', 'a', 'herse"', 'should', 'several', 'thereby', 'few', 'sometime', 'within', 'him', 'their', 'i', 'thereafter', 'towards', 'besides', 'some', 'con', 'is', 'of', 'namely', 'than', 'anyway', 'onto', 'therein', 'whatever', 'part', 'mostly', 'becoming', 'enough', 're', 'ltd', 'again', 'this', 'myse"', 'those', 'whoever', 'empty', 'thin', 'only', 'an', 'its', 'whole', 'behind', 'has', 'former', 'noone', 'wherein', 'fifteen', 'bill', 'due', 'since', 'made', 'why', 'others', 'out', 'cannot', 'side', 'system', 'am', 'show', 'least', 'seeming', 'nowhere', 'else

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [47]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
reviews_stemmed = reviews["reviewText"].str.split().apply(lambda review: " ".join([stemmer.stem(word) for word in review]))
reviews["reviewText"] = reviews_stemmed
reviews["reviewText"]

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [74]:
import numpy as np
reviews_overall_1_2 = reviews[reviews["overall"].between(1, 2, inclusive="both")]
reviews_overall_1_2['reviewText'].to_csv('neg.txt', index=False, header=False)
reviews_overall_1_2["reviewText"]

1          suck bare pick definit car pretti dont wast money
2           write short one blew 2 fuse car appar demand 12v
7                 2017 outback everytim tri use im blow fuse
10         just expect mabi expect high work just good en...
13                               junk lighter fell apart box
                                 ...                        
1711473    bright all 5 year old 3600lm headlight brighte...
1711477                                     bright dont long
1711491    unfortun order read review tray flexibl materi...
1711496          light burn right away request return amazon
1711513    cheapli made known price wire super break easi...
Name: reviewText, Length: 132298, dtype: str

In [75]:
reviews_overall_4_5 = reviews[reviews["overall"].between(4, 5, inclusive="both")]
reviews_overall_4_5['reviewText'].to_csv('pos.txt', index=False, header=False)
reviews_overall_4_5["reviewText"]

0          wrote review manufactur contact explain use th...
4                                                 ok doe job
5                       3 big dog great ford transit connect
8                                          good suction last
9                                      love itwork great wow
                                 ...                        
1711514                                 fast ship work great
1711515     fit isnt great relay hard press connector mechan
1711516    bought auxiliari horn car need run relay guy f...
1711517    way better stock nice bright white super easi ...
1711518    great product fast ship awesom commun product ...
Name: reviewText, Length: 1476572, dtype: str

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**